### ISSUE TITLE
Restoring all axis after radarChart.filterAxes(1); 

### ISSUE THREAD

**Issue by Edouard-Legoupil** [TennisVisuals/updating-radar-chart#5]
Hi There,

In the demo, there's no illustration of how we can restore an axis after a `.filterAxes(1);`

What shall I do for that?

Thanks

**Comment by TennisVisuals** [comment]
Did you get it sorted?

**Comment by Edouard-Legoupil** [comment]
yes -- thanks: http://edouard-legoupil.github.io/5A-Analysis/

**Comment by Edouard-Legoupil** [comment]
if you have any suggestions, let me know

**Comment by Edouard-Legoupil** [comment]
for instance, I would like to customize the labels on the axis 1: strongly disagree, 2: disagree, 3: neither disagree, neither agree, 4: agree, 5: strongly agree. Any hints on how to do that?

**Comment by TennisVisuals** [comment]
nice!  I think it would be good to be able to control the transitions so that text/commentary can be read more leisurely.  Also the tooltips don't show up that well (which is my fault).  In one of my other blocks I enabled pluggable tooltips which would be nice to have in the radar chart.  I haven't looked at this code in a long time, but I think the labels should be easily customizable.

**Comment by TennisVisuals** [comment]
I think right now the labels/legends are defined solely by the data.  You would have to change the data on the way in or modify the radarChart source to specify an override value...
